# SPDX-FileCopyrightText: Copyright © 2025 hashcatHitman
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

allowed-duplicate-crates = [
    "block-buffer",
    "crypto-common",
    "digest",
    "sha2",
    "hashbrown",
    "cpufeatures",
    "h2",
    "http",
    "http-body",
    "hyper",
    "hyper-rustls",
    "rustls",
    "rustls-webpki",
    "socket2",
    "tokio-rustls",
    "windows-sys",
    "windows-targets",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_i686_gnu",
    "windows_i686_gnullvm",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
]
allow-dbg-in-tests = true
allow-expect-in-tests = true
allow-indexing-slicing-in-tests = true
allow-panic-in-tests = true
allow-print-in-tests = true
allow-renamed-params-for = []
allow-unwrap-in-tests = true
avoid-breaking-exported-api = false
check-private-items = true
upper-case-acronyms-aggressive = true
warn-unsafe-macro-metavars-in-private-macros = true
