
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.hashcatHitman]
url = "https://raw.githubusercontent.com/hashcatHitman/supply-chain/main/audits.toml"

[[exemptions.anyhow]]
version = "1.0.102"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.11.0"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.chacha20]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.equivalent]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.foldhash]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.15.5"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.16.1"
criteria = "safe-to-deploy"

[[exemptions.heck]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.id-arena]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "2.13.0"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.17"
criteria = "safe-to-deploy"

[[exemptions.leb128fmt]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.182"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.29"
criteria = "safe-to-deploy"
